[package]
name = "tinyevm"
version = "1.0.4"
edition = "2024"

[lib]
name="tinyevm"
crate-type = ["cdylib", "rlib"]
path="src/lib.rs"

[dependencies]
openssl = "0.10.72"
ring = "0.17.12"

eyre = { version = "0.6.12" }
hex = "0.4.3"
lazy_static = "1.5.0"
libc = "0.2.172"
maplit = "1.0.2"
num-bigint = "0.4.6"
# primitive-types = "0.12.2"
pyo3 = { version = "0.24.2", features = ["extension-module", "num-bigint", "serde", "eyre"] }
revm = { version = "19.0.0", features = ["hashbrown", "optional_no_base_fee", "serde", "serde-json", "optional_eip3607", "optional_block_gas_limit"] }
ruint = "1.14.0"
serde = { version = "1.0.219", features = ["serde_derive", "derive"] }
serde_json = "1.0.140"
sha3 = "0.10.8"
simple_logger = "5.0.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
# ethers = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
# ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
# ethers-contract = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
# ethers-providers = { git = "https://github.com/gakonst/ethers-rs" }
# ethers-middleware = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
dotenv = "0.15.0"
thread_local = "1.1.8"
tokio = { version = "1.44.2", features = ["full"] }
strum_macros = "0.26.4"
redis = { version= "0.25.4", optional = true}
alloy = { version = "0.12", features = ["full"] }
uuid = { version = "1.16.0", features = ["v4"] }
hex-literal = "0.4.1"
hashbrown = { version = "0.15.3", features = ["serde"] }

[dev-dependencies]
criterion = {version="0.5", features=["html_reports"] }
rand = "0.9.1"

[features]
default = ["with-serde"]
redis=["dep:redis"]
with-serde = []

[[bench]]
name = "general"
harness = false

[[bench]]
name = "deploy"
harness = false

[[bench]]
name = "infinite_loop"
harness = false

[[bench]]
name = "function"
harness = false

[[bench]]
name = "conversion"
harness = false

[[bench]]
name = "simple"
harness = false

[profile.bench]
debug = false
